### ISSUE TITLE
Correct answer shown before submitting a guess.

### ISSUE THREAD

**Issue by amitsagtani97** [divyanshu-rawat/Javascript-Work#1]
The Correct answer is shown at top left corner on screen before the player makes his guess.
![bug](https://user-images.githubusercontent.com/22855579/27011861-e63288b2-4ee2-11e7-8b3c-26262fa05be4.png)

**Comment by divyanshu-rawat** [comment]
@amitsagtani97 assigned you Now you can work on it.
Actually, the correct answer was shown just for verification.
But I think we can ignore it now.
Feel free to send a Pull request.
